name: flutter_bloc_devtools
description: Remote DevTools for flutter_bloc. This package connects all Bloc (not working with Cubit) to the Remote Devtools Server, allowing the developer to inspect changes to the Blocs during runtime.
homepage: https://github.com/andrea689/flutter_bloc_devtools/
version: 0.1.0

environment:
  sdk: '>=2.3.0 <3.0.0'
  
dependencies:
  bloc: ^6.1.0
  socketcluster_client: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0

