name: flutter_bloc_devtools
description: Remote DevTools for flutter_bloc. This package connects all Bloc to the Remote Devtools Server, allowing the developer to inspect changes to the Blocs during runtime.
homepage: https://github.com/andrea689/flutter_bloc_devtools/
version: 0.1.3

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  bloc: ^7.0.0
  socketcluster_client: ^0.3.0

dev_dependencies:
  pedantic: ^1.11.1

